### ISSUE TITLE
Application is crashing (ModuleNotFoundError: No module named 'helper_funcs.help_Nekmo_ffmpeg')

### ISSUE THREAD

**Issue by Mahmud8421** [FayasNoushad/URL-Uploader#2]
Here is the full error log:

Traceback (most recent call last):
2021-05-30T03:59:41.469745+00:00 app[worker.1]:   File "/app/bot.py", line 25, in <module>
2021-05-30T03:59:41.469813+00:00 app[worker.1]:     app.run()
2021-05-30T03:59:41.469819+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/pyrogram/methods/utilities/run.py", line 61, in run
2021-05-30T03:59:41.469971+00:00 app[worker.1]:     self.start()
2021-05-30T03:59:41.469972+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/pyrogram/sync.py", line 56, in async_to_sync_wrap
2021-05-30T03:59:41.470101+00:00 app[worker.1]:     return loop.run_until_complete(coroutine)
2021-05-30T03:59:41.470102+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
2021-05-30T03:59:41.470375+00:00 app[worker.1]:     return future.result()
2021-05-30T03:59:41.470379+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/pyrogram/methods/utilities/start.py", line 68, in start
2021-05-30T03:59:41.470500+00:00 app[worker.1]:     await self.initialize()
2021-05-30T03:59:41.470521+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/pyrogram/methods/auth/initialize.py", line 44, in initialize
2021-05-30T03:59:41.470626+00:00 app[worker.1]:     self.load_plugins()
2021-05-30T03:59:41.470651+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/site-packages/pyrogram/client.py", line 715, in load_plugins
2021-05-30T03:59:41.470933+00:00 app[worker.1]:     module = import_module(module_path)
2021-05-30T03:59:41.470935+00:00 app[worker.1]:   File "/app/.heroku/python/lib/python3.9/importlib/__init__.py", line 127, in import_module
2021-05-30T03:59:41.471042+00:00 app[worker.1]:     return _bootstrap._gcd_import(name[level:], package, level)
2021-05-30T03:59:41.471043+00:00 app[worker.1]:   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
2021-05-30T03:59:41.471168+00:00 app[worker.1]:   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
2021-05-30T03:59:41.471246+00:00 app[worker.1]:   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
2021-05-30T03:59:41.471326+00:00 app[worker.1]:   File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
2021-05-30T03:59:41.471407+00:00 app[worker.1]:   File "<frozen importlib._bootstrap_external>", line 855, in exec_module
2021-05-30T03:59:41.471573+00:00 app[worker.1]:   File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
2021-05-30T03:59:41.471668+00:00 app[worker.1]:   File "/app/plugins/cb_buttons.py", line 8, in <module>
2021-05-30T03:59:41.471764+00:00 app[worker.1]:     from plugins.youtube_dl_button import youtube_dl_call_back
2021-05-30T03:59:41.471765+00:00 app[worker.1]:   File "/app/plugins/youtube_dl_button.py", line 24, in <module>
2021-05-30T03:59:41.471872+00:00 app[worker.1]:     from helper_funcs.help_Nekmo_ffmpeg import generate_screen_shots
2021-05-30T03:59:41.471876+00:00 app[worker.1]: ModuleNotFoundError: No module named 'helper_funcs.help_Nekmo_ffmpeg'

**Comment by FayasNoushad** [comment]
Added files. Deploy again.
